# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphdatapoints',
            name='user',
        ),
        migrations.DeleteModel(
            name='GraphDataPoints',
        ),
    ]
